version: '3.8'

services:
  neet_alert_bot:
    build: .
    container_name: neet_alert_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    mem_limit: 256m